spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_platform?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: api_platform
    password: 1122*aabb
#--------------------------------------------------------------
#客户端SDK配置
api:
  client:
    gateway-host: http://localhost:9000
#--------------------------------------------------------------